
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  name: 'viewport',
  content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
